config/routes.rb
Rails.application.routes.draw do
  resources :coughs

  root 'coughs#new'

end

app/models/cough.rb
class Cough < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coughs_controller.rb
class CoughsController < ApplicationController
  before_action :set_cough, only: [:show, :edit, :update, :destroy]

  # GET /coughs
  # GET /coughs.json
  def index
    @coughs = Cough.all
  end

  # GET /coughs/1
  # GET /coughs/1.json
  def show
    @cough = Cough.find(params[:id])
  end

  # GET /coughs/new
  def new
    @cough = Cough.new
  end

  # GET /coughs/1/edit
  def edit
  end

  # POST /coughs
  # POST /coughs.json
  def create
    @cough = Cough.new(cough_params)
    respond_to do |format|
      if @cough.save
        format.html { redirect_to @cough, notice: 'Cough was successfully created.' }
        format.json { render :show, status: :created, location: @cough }
      else
        format.html { render :new }
        format.json { render json: @cough.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coughs/1
  # PATCH/PUT /coughs/1.json
  def update
    respond_to do |format|
      if @cough.update(cough_params)
        format.html { redirect_to @cough, notice: 'Cough was successfully updated.' }
        format.json { render :show, status: :ok, location: @cough }
      else
        format.html { render :edit }
        format.json { render json: @cough.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coughs/1
  # DELETE /coughs/1.json
  def destroy
    @cough.destroy
    respond_to do |format|
      format.html { redirect_to coughs_url, notice: 'Cough was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cough
      @cough = Cough.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cough_params
      params.require(:cough).permit(:type, :frequency, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coughs_helper.rb
module CoughsHelper
end

app/views/coughs/_form.html.erb
<%= form_for(@cough) do |f| %>
  <% if @cough.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cough.errors.count, "error") %> prohibited this cough from being saved:</h2>

      <ul>
      <% @cough.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :frequency %><br>
    <%= f.number_field :frequency %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coughs/edit.html.erb
<h1>Editing Cough</h1>

<%= render 'form' %>

<%= link_to 'Show', @cough %> |
<%= link_to 'Back', coughs_path %>

app/views/coughs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coughs</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Frequency</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coughs.each do |cough| %>
      <tr>
        <td><%= cough.type %></td>
        <td><%= cough.frequency %></td>
        <td><%= cough.age %></td>
        <td><%= link_to 'Show', cough %></td>
        <td><%= link_to 'Edit', edit_cough_path(cough) %></td>
        <td><%= link_to 'Destroy', cough, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cough', new_cough_path %>

app/views/coughs/new.html.erb
<div class="home">
  <%= form_for(@cough) do |f| %>

    <div class="screen">
      <div id="visualizer">
      </div>
      <div class="caption">
        <p><strong>TAP GREEN BUTTON TO RECORD</strong></p>
      </div>
      <div class="question" >
        <h2>How frequently are you coughing?</h2>
          <select class="question-frequency">
            <option value="0">Rarely</option>
            <option value="1">A few times a day</option>
            <option value="2">A few times per hour</option>
            <option value="3">All the time</option>
          </select>
        <%= f.hidden_field :frequency %>
      </div>
    </div>

    <div class="record-button">
    </div>
    <div class="stop-record">
    </div>


  <% end %>


</div>

app/views/coughs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @cough.type %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @cough.frequency %>
</p>

<p>
  <strong>Age:</strong>
  <%= @cough.age %>
</p>

<%= link_to 'Edit', edit_cough_path(@cough) %> |
<%= link_to 'Back', coughs_path %>

app/views/layouts/_nav.html.erb
<div class="nav">
  <%= image_tag 'logo-white.png', class: 'logo' %>

  <div class="hamburger">
    <div class="hamburger-bar">
    </div>
    <div class="hamburger-bar">
    </div>
    <div class="hamburger-bar">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ahem</title>
  <link href='https://fonts.googleapis.com/css?family=Quicksand:400,700,300' rel='stylesheet' type='text/css'>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.12/p5.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.13/addons/p5.sound.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>

  <%= yield %>

</body>
</html>